config/routes.rb
PetSearch::Application.routes.draw do
  root 'pets#index'

  resources :pets

end

app/models/pet.rb
class Pet
	include Mongoid::Document
	include Mongoid::Timestamps
	include Geocoder::Model::Mongoid

  field :name, :default => " "
  field :age 
  field :gender
  field :size
  field :description
  field :species #either 'Cat' or 'Dog'
  field :status  #'Available', 'Fostered', 'Adopted', 'Deleted'
  field :organization_name
  field :is_housebroken, type: Boolean
  field :is_housetrained, type: Boolean
  field :is_hypoallergenic, type: Boolean
  field :tail
  field :color
  field :primary_breed  
  field :secondary_breed  
  field :hair_length
  field :contact_street_address
  field :contact_city
  field :contact_state
  field :contact_zipcode
  field :contact_phone
  field :contact_fax
  field :contact_email
  field :address 
  field :coordinates, :type => Array
  geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pet }
      else
        format.html { render action: 'new' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :age, :size)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetSearch</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.1.1/list.min.js"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "header" %>

  <%= yield %>
</body>
</html>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/_header.html.erb
<header id="header">
  <div class="header-holder">
    <div class="header-frame">
      <div class="header-info">
        <strong class="logo"><%= link_to root_path %></strong>
        <div class="social-networks">
          <strong class="title">Sniff Us Out</strong>
          <ul>
            <li class="facebook"><%= link_to "Facebook", "http://www.facebook.com/petstablished" %></li>
            <li class="twitter"><%= link_to "Twitter", "http://www.twitter.com/petstablished" %></li>
            <li class="instagram"><%= link_to "Instagram", "http://www.instagram.com/petstablished" %></li>
          </ul>
        </div>
      </div>
      <h1 style="text-shadow:1px 1px 6px black">Petstablished!</h1><br>
      <div class="btn-area">
        <%= link_to "Sign Up", "http://www.petstablished.com/signups/new", class: "btn btn-demo" %>
        <%= link_to "Newsletter", "http://www.petstablished.com/newsletters/new", class: "btn btn-demo" %>
      </div>
    </div>
  </div>
  <%= image_tag "header-bg.jpg", class: "main-img" %>
</header>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<div id="pet-list">
	<div class="list-tools">
		<h1>Find Your New Best Friend</h1>
		<div class="tools">
		  <input class="search" placeholder="Search" /><br>
			<span class="section">
		    <input type="radio" id="radio1" name="age" value="Young">
		    <label for="radio1">Young</label>
		    <input type="radio" id="radio2" name="age" value="Adult">
		    <label for="radio2">Adult</label>
		    <input type="radio" id="radio3" name="age" value="Senior">
		    <label for="radio3">Senior</label>
			</span>
	    <span class="section">
		    <input type="radio" id="radio4" name="size" value="Small">
		    <label for="radio3">Small</label>
		    <input type="radio" id="radio5" name="size" value="M">
		    <label for="radio3">Medium</label>
		    <input type="radio" id="radio6" name="size" value="L">
		    <label for="radio3">Large</label>
    	</span>
    	<span class="section">
		    <input type="radio" id="radio7" name="species" value="Dog">
		    <label for="radio3">Cat</label>
		    <input type="radio" id="radio8" name="species" value="Cat">
		    <label for="radio3">Dog</label>
		  </span>
<br>
	    <button class="sort" data-sort="name">
	      Sort by name
	    </button>
	    <button class="sort" data-sort="age">
	      Sort by age
	    </button>
	    <button class="sort" data-sort="size">
	      Sort by size
	    </button>
	    <button class="sort" data-sort="species">
	      Sort by species
	    </button>
	  </div>
	</div>
  <ul class="list">
		<%= @pets.each do |pet| %>
			<ul class="pet-entry">
					<div id="profile">
						<% if pet.species == "Cat" %>
							<%= image_tag "cat-profile.jpg" %>
						<% else %>
							<%= image_tag "puppy-profile.jpg" %>
						<% end %>
					</div>
				<li class="name"><h3>Hi, I'm <strong><%= pet.name %></strong></h3> </li>
				<li class="age">Age: <%= pet.age %> </li>
				<li class="size">Size: <%= pet.size %> </li>
				<li class="species">Species: <%= pet.species %> </li>
				<li class=""> Status: <%= pet.status %> </li>
				<li class=""> Organization: <%= pet.organization_name%> </li>
				<li class=""> Housebroken? <%= pet.is_housebroken %> </li>
				<li class=""> Housetrained? <%= pet.is_housetrained %> </li>
				<li class=""> Hypoallergenic? <%= pet.is_hypoallergenic %> </li>
				<li class=""> Color: <%= pet.color %> </li>
				<li class=""> Breed(s): <%= pet.primary_breed %> - <%= pet.secondary_breed %> </li>
				<li class=""> Hair: <%= pet.hair_length %> </li>
				<li class=""> City: <%= pet.contact_city %> </li>

				<div class="profile-page"><%= link_to 'View Complete Profile', pet %> </div>
			</ul>
		<% end %>
	</ul>
	<p><%= link_to 'Add a New Pet', new_pet_path %></p>
	<ul class="pagination"></ul>
</div>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<%= @pet.name %>
  <%= @pet.age  %>
  <%= @pet.gender %>
  <%= @pet.size %>
  <%= @pet.description %>
  <%= @pet.species %>
  <%= @pet.status   %>
  <%= @pet.organization_name %>
  <%= @pet.is_housebroken %>
  <%= @pet.is_housetrained %>
  <%= @pet.is_hypoallergenic %>
  <%= @pet.tail %>
  <%= @pet.color %>
  <%= @pet.primary_breed   %>
  <%= @pet.secondary_breed   %>
  <%= @pet.hair_length %>
  <%= @pet.contact_street_address %>
  <%= @pet.contact_city %>
  <%= @pet.contact_state %>
  <%= @pet.contact_zipcode %>
  <%= @pet.contact_phone %>
  <%= @pet.contact_fax %>
  <%= @pet.contact_email %>
  <%= @pet.address  %>
  <%= @pet.coordinates %>


<%= link_to 'Back', pets_path %>